### ISSUE TITLE
Visualisation not running

### ISSUE THREAD

**Issue by Charodej** [dukess/bsb_lan_ajax#1]
Hello,
Followed instructions but I am only getting always this screen
![1](https://user-images.githubusercontent.com/71496568/93588771-2c3b5b00-f9ac-11ea-8771-8eca8654440c.png)
Any help?
BSB_LAN server works without ajax but always with ajax this issue.

Thank you so much,

Ch

**Comment by dukess** [comment]
Sorry for deeeeelaaaayeeed answer. I just didn't notice the message. I didn't expect this.

**Comment by dukess** [comment]
If i understand you cannot download ajax.html? 
https://github.com/dukess/bsb_lan_ajax/raw/master/ajax.html

**Comment by Charodej** [comment]
Using arduino due, everything on the card that should be, latest bsb-lan version works well with its visualisation but when trying to switch to ajax.html always getting to this screen. Not possible to see your visualisation. I read, checked and tried few times and always with no luck.

**Comment by dukess** [comment]
I made release with all needed files. You can try to download it.
https://github.com/dukess/bsb_lan_ajax/releases/download/v1.0.0/bsb-lan-ajax.zip
If nothing changes after installation, I ask you to send me a screenshot from file Explorer with the contents of the SD card

**Comment by Charodej** [comment]
Works! Thank you so much.

**Comment by dukess** [comment]
Welcome!
